### PR TITLE
brick: fix redefined flag

### PR DESCRIPTION
**Pull request by kroggen**
Fix error "redefined flag: v" on `brick`

### CODE REVIEW

**Comment by kroggen** [comment]
@hayarobi 

I guess this started happening when the master and develop branches were merged

The `v` flag is already being used in the `log` module, so it gives the error "flag redefined: v" when we run `brick` 

I just renamed the flag to `b` on brick

Do you have any other idea?

**Comment by hayarobi** [comment]
How about using capital `V`?

**Review by hayarobi — APPROVED** [review]
lgtm

**Comment by kroggen** [comment]
Good idea! I changed it to `V`

As you can see, both the full and short workflows were triggered with this new commit. Only the full one should run. I made a fix to this in another PR

**Pull request merged**
