### PR TITLE
disable CI run on PR edit

### PR DESCRIPTION
**Pull request by kroggen**
When the title or the first comment of a PR is edited, a new CI/CD workflow run is activated

This is annoying, uses CI time without need, and marks some PRs as failing when the run is cancelled

This PR disable this behavior

When the base of a PR is modified, then we need to start a new run manually, until GitHub has a solution for the problem

### CODE REVIEW

**Comment by gokch** [comment]
What do you think about remove verbose option when go tests? Verbose test is confusing and make hard to find error line.

**Comment by kroggen** [comment]
I agree

**Comment by kroggen** [comment]
@hayarobi 
Do you agree?
Should the verboseness be removed also from the "code coverage" test?

**Review by hayarobi — APPROVED** [review]
lgtm

**Pull request merged**
