### PR TITLE
fix github actions short test workflow

### PR DESCRIPTION
**Pull request by kroggen**
do not run short test on pull requests

### CODE REVIEW

**Comment by kroggen** [comment]
This change fix the problem of Short Tests running on pull requests

The previous method was not working when a new commit/push is added to an existing pull request

**Comment by hayarobi** [comment]
In my code, if the pushed commit had the same hash, the build and test will be skipped. Your change excludes short tests in case of pull request because it performs complete tests. These two `jobs` has somewhat different purpose. Is there any way to combine both?

**Comment by kroggen** [comment]
For which cases the current method would be useful?

I suspect that if the commits are rebased or cherry-picked to another branch, the hash will be different, right?

**Review by hayarobi — APPROVED** [review]
lgtm

**Pull request merged**
