### PR TITLE
refactoring for encoding logic

### PR DESCRIPTION
**Pull request by gokch**
## What is changed?
small refactoring about encode ( hex, base58, base58check, base64, gob )
replace encode logic to using internal package

### CODE REVIEW

**Comment by kroggen** [comment]
Why is the `GobDecode` in the `common` package instead of together with the others in `enc`?

Is there some requirement for that?

**Comment by kroggen** [comment]
The conversion from `enc.ToString` to `enc.B58Encode` makes it clear what is the encoding format.

I am just not sure if the long name would not be better, like `Base58` instead of `B58`

---

I would prefer to use names like this instead of `enc`:

```
base64.Encode
base58.Encode
base58check.Encode
hex.Encode
```

So all would have a consistent usage, with {format}.(Encode|Decode)

This would require to have each of these inside of "enc", like "enc/base64", "enc/hex"...

**Comment by kroggen** [comment]
In [types/common.go](https://github.com/aergoio/aergo/blob/14d88329b0102f7b5c7888779357ae02e048e98b/types/common.go) we can still find `EncodeB64` and `EncodeB58`

**Comment by gokch** [comment]
> Why is the `GobDecode` in the `common` package instead of together with the others in `enc`?
> 
> Is there some requirement for that?

in before enc package was just b58 encode / decode. i`ll move gob function from common to enc.

**Comment by gokch** [comment]
> In [types/common.go](https://github.com/aergoio/aergo/blob/14d88329b0102f7b5c7888779357ae02e048e98b/types/common.go) we can still find `EncodeB64` and `EncodeB58`

internal package doesn`t reveal for other repository, but indexer / tx_replay should use encode/decode logic. so it is good to leave in types.

**Review by kroggen — APPROVED** [review]

**Comment by kroggen** [comment]
It appears OK to me

@hayarobi  What do you think?

**Comment by gokch** [comment]
it need sync test before merged @kslee8282

**Comment by kslee8282** [comment]
> it need sync test @kslee8282

Nov  6 06:07:57.931 INF ../go/aergo/cmd/aergosvr/aergosvr.go:100 > AERGO SVR STARTED branch=feature/encoding module=asvr revision=04c5a261
start sync mainnet

**Review by kroggen — APPROVED** [review]

**Comment by kslee8282** [comment]
sync success

**Comment by kroggen** [comment]
Simple conflict resolved

**Pull request merged**
