### PR TITLE
add name_service.resolve()

### PR DESCRIPTION
**Pull request by kroggen**

### CODE REVIEW

**Comment by hayarobi** [comment]
Please merge to develop branch first.

**Comment by kroggen** [comment]
This is lacking tests. Only merge after passing the tests

**Comment by kroggen** [comment]
To run the integration tests:

Install dependencies: (Ubuntu and Debian)

```
apt update
apt install jq m4 make cmake -y
```

Install dependencies: (Alpine)

```
apk add jq m4 make cmake
```

Run tests:

```
git submodule update --recursive
make
cd tests
./run_tests.sh
```

**Comment by kroggen** [comment]
Feel free to change the base of this PR to `release/2.4.4`, if it is a more suitable destination

**Comment by kroggen** [comment]
@hayarobi should this PR be based/merged onto the `release/2.4.4` branch?

**Comment by kroggen** [comment]
This lacks regression tests for computed gas

**Review by hayarobi — APPROVED** [review]
lgtm

**Pull request merged**
