### PR TITLE
add state dump

### PR DESCRIPTION
**Pull request by gokch**
# What is changed?
support dump for account, contract, contract storage in state trie

# Is there risk of fork?
no. it is for debug and test only.

### CODE REVIEW

**Comment by kroggen** [comment]
Is this for the API?
Or to be used locally?

**Comment by gokch** [comment]
> Is this for the API? Or to be used locally?

it used only locally.
maybe it can used when error occured.

**Review by kroggen — APPROVED** [review]
Appears to not interfere with existing code

**Comment by kroggen** [comment]
There is also this: [aergoio/state-tools](https://github.com/aergoio/state-tools)

**Comment by gokch** [comment]
snapshot migration is in progress, so it can add after 2.5.0 release.

**Pull request merged**
