### PR TITLE
fix: use prefix on state trie keys

### PR DESCRIPTION
**Pull request by kroggen**

### CODE REVIEW

**Comment by gokch** [comment]
it need sync test from genesis block.

**Comment by kslee8282** [comment]
> it need to pass sync test from new empty db. @kslee8282

Oct 30 04:04:01.342 INF ../go/aergo/cmd/aergosvr/aergosvr.go:100 > AERGO SVR STARTED branch=fix/state-trie-keys module=asvr revision=d17db23a

start sync mainnet

**Comment by kslee8282** [comment]
testnet sync (11821274 / 111859080)
mainnet sync (81317246 / 142831796)

**Comment by gokch** [comment]
it can merged after all node ready to migration on next version.

**Review by gokch — APPROVED** [review]
db migration is ready.

**Pull request merged**
