### PR TITLE
review and comments on state module

### PR DESCRIPTION
**Pull request by kroggen**
* Add new comments and rearrange existing ones
* Move common code to a function
* Remove `lua_pushvalue()` apparently unused

### CODE REVIEW

**Review by hayarobi — APPROVED** [review]
lgtm

**Comment by kslee8282** [comment]
start sync  mainnet
Oct 18 09:09:48.599 INF ../go/aergo/cmd/aergosvr/aergosvr.go:100 > AERGO SVR STARTED branch=topic/code-comments-review module=asvr revision=e82d79f0

**Comment by kslee8282** [comment]
start sync testnet
Oct 18 09:13:21.760 INF ../go/aergo/cmd/aergosvr/aergosvr.go:100 > AERGO SVR STARTED branch=topic/code-comments-review module=asvr revision=e82d79f0

**Comment by hayarobi** [comment]
kslee reported that the synctest was failed, by different gas usage of a tx in testnet.

```
Oct 19 05:53:21.686 INF ../go/aergo/syncer/blockprocessor.go:271 > request connecting block to chainsvc hash=DN1sLfC77iMVdvSDumirTXzMKbCqkdYXaJrQPXGqwJuW module=syncer no=70212143
Oct 19 05:53:21.686 DBG ../go/aergo/contract/vm.go:834 > call abi="{\"name\":\"delTransporter\",\"args\":[\"AmNS6AvN8sc3DwtJtezZnZ16ZK3otpJa8WeZVU4SvHkBJAkPH8ia\"]}" contract=Amguvzvgk8dHh3q7mZGabdgmsCD2FDQYj8WPmkQ1guV1HNNST4U5 module=contract
Oct 19 05:53:21.686 DBG ../go/aergo/contract/lstate_factory.go:51 > LState acquired module=contract
Oct 19 05:53:21.687 DBG ../go/aergo/contract/vm.go:381 > gas information gas used=0 lua vm=loaded module=contract
Oct 19 05:53:21.687 DBG ../go/aergo/contract/vm.go:258 > gas information gas used=47182 lua vm=executed module=contract
Oct 19 05:53:21.687 DBG ../go/aergo/contract/lstate_factory.go:58 > LState released module=contract
Oct 19 05:53:21.687 DBG ../go/aergo/contract/vm.go:273 > LState created module=contract
Oct 19 05:53:21.688 ERR ../go/aergo/chain/blockvalidator.go:165 > block root hash validation failed block=DN1sLfC77iMVdvSDumirTXzMKbCqkdYXaJrQPXGqwJuW hdrroot=JxB5tYixC1oZ5mkvZQ6SRxe8XA1hYArR71exbPGm4XP module=chain sdbroot=CMAW5TKuqVTt2HvkidXFKJER95PAXQJg75dKQ7kMrbGA
Oct 19 05:53:21.715 ERR ../go/aergo/chain/chainhandle.go:337 > failed to execute block error="Block verify failed, because state root hash is not equal" hash=DN1sLfC77iMVdvSDumirTXzMKbCqkdYXaJrQPXGqwJuW module=chain
Oct 19 05:53:21.715 ERR ../go/aergo/chain/chainhandle.go:519 > add errored block to errBlocks lru error="Block verify failed, because state root hash is not equal" evicted=false hash=DN1sLfC77iMVdvSDumirTXzMKbCqkdYXaJrQPXGqwJuW module=chain no=70212143
Oct 19 05:53:21.715 ERR ../go/aergo/chain/chainservice.go:652 > failed to add block error="Block verify failed, because state root hash is not equal" hash=DN1sLfC77iMVdvSDumirTXzMKbCqkdYXaJrQPXGqwJuW module=chain no=70212143
```
The block no 70212143 `DN1sLfC77iMVdvSDumirTXzMKbCqkdYXaJrQPXGqwJuW` contains a tx `CSwCg4KoJnrnytKHWPhqzdQ2ZBgkRcFwpMWRYYeKeAqe`, which uses gas 147224 in current release, but looks use 147182 in the branch of this PR.
We will investigate this in next week.

**Comment by kroggen** [comment]
OK, I reverted the commit that was probably causing it. So a new test can be made.
The sync test was made only with this branch?

**Comment by kslee8282** [comment]
> OK, I reverted the commit that was probably causing it. So a new test can be made. The sync test was made only with this branch?

yes. it is failed only caused this branch.

**Comment by kroggen** [comment]
I fixed the problem. It is now passing on testnet using tx-replay

A new sync test can be made, but only after done on #287 as it is more important

**Comment by kslee8282** [comment]
> topic/code-comments-review

start sync mainnet
Oct 24 04:00:25.644 INF ../go/aergo/cmd/aergosvr/aergosvr.go:100 > AERGO SVR STARTED branch=topic/code-comments-review module=asvr revision=4039bb15

**Comment by kslee8282** [comment]
> I fixed the problem. It is now passing on testnet using tx-replay
> 
> A new sync test can be made, but only after done on #287 as it is more important

Passing through unsynchronized heights
mainnt : 85826886 / 142400469 > 63502024 
testnet : 77149000 / 111405923 > 70212142

**Comment by kslee8282** [comment]
sync success

**Review by gokch — APPROVED** [review]

**Pull request merged**
