### PR TITLE
system.date() and system.time()

### PR DESCRIPTION
**Pull request by kroggen**
This PR prepares the `system.date()` and `system.time()` functions to be made public

The result of these functions must be deterministic

### CODE REVIEW

**Comment by kroggen** [comment]
Check the discussion [here](https://github.com/aergoio/aergo/discussions/271)

**Comment by kroggen** [comment]
@kslee8282 This PR is also ready to run a sync test

**Comment by kslee8282** [comment]
> @kslee8282 This PR is also ready to run a sync test

start sync testnet
Oct 23 02:12:48.586 INF ../go/aergo/cmd/aergosvr/aergosvr.go:100 > AERGO SVR STARTED branch=topic/datetime module=asvr revision=3293a551

**Comment by kroggen** [comment]
@kslee8282 
Did this pass the sync tests?

**Comment by kslee8282** [comment]
sync success

**Comment by kroggen** [comment]
@hayarobi @gokch 
The notes about this PR is [here](https://github.com/aergoio/aergo/discussions/271)

**Review by gokch — APPROVED** [review]

**Review by hayarobi — APPROVED** [review]
lgtm

**Pull request merged**
